// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn1wEicGaTMMNyMokbaFj-qT8HOauDK4Q',
    appId: '1:889778409868:web:213cbdd379bd19e1e686a9',
    messagingSenderId: '889778409868',
    projectId: 'udemy-course-a3637',
    authDomain: 'udemy-course-a3637.firebaseapp.com',
    storageBucket: 'udemy-course-a3637.appspot.com',
    measurementId: 'G-YSJ90JLB6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBjV_RzNv5AMVI8Yphmdo1bC8SWld2Jw4',
    appId: '1:889778409868:android:ae57eabc51bdd9f5e686a9',
    messagingSenderId: '889778409868',
    projectId: 'udemy-course-a3637',
    storageBucket: 'udemy-course-a3637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB10Bxcm9CsLiiI1b9x1FXf2bMjq7tvMQk',
    appId: '1:889778409868:ios:4c3c5e88ab9f3c05e686a9',
    messagingSenderId: '889778409868',
    projectId: 'udemy-course-a3637',
    storageBucket: 'udemy-course-a3637.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB10Bxcm9CsLiiI1b9x1FXf2bMjq7tvMQk',
    appId: '1:889778409868:ios:001a1ae2fb629dd9e686a9',
    messagingSenderId: '889778409868',
    projectId: 'udemy-course-a3637',
    storageBucket: 'udemy-course-a3637.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
